#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Shunt — Blue-green deploy script
#
# Performs a zero-downtime blue-green deployment:
#   1. Determines current active color from cfg/active-color
#   2. Builds a fresh Docker image
#   3. Starts the inactive color container
#   4. Waits for /healthz to return 200 (60s timeout)
#   5. Switches Caddy to the new color and reloads
#   6. Updates cfg/active-color marker
#   7. Drains and stops the old color after a 30s grace period
#
# Idempotent: safe to re-run at any point in the flow.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ACTIVE_COLOR_FILE="$PROJECT_ROOT/cfg/active-color"
CADDYFILE="$PROJECT_ROOT/cfg/Caddyfile"
COMPOSE_FILE="$PROJECT_ROOT/docker-compose.yml"

HEALTH_TIMEOUT=60
DRAIN_SECONDS=30
HEALTH_CHECK_INTERVAL=2

# ── Helpers ──────────────────────────────────────────────────────────────────

log() {
    local level="$1"; shift
    printf '{"time":"%s","level":"%s","msg":"%s"}\n' \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$level" "$*"
}

info()  { log "info"  "$@"; }
warn()  { log "warn"  "$@"; }
error() { log "error" "$@"; }

# ── Determine colors ─────────────────────────────────────────────────────────

get_current_color() {
    if [ -f "$ACTIVE_COLOR_FILE" ]; then
        cat "$ACTIVE_COLOR_FILE"
    else
        echo "blue"
    fi
}

next_color() {
    local current="$1"
    if [ "$current" = "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# ── Health check ─────────────────────────────────────────────────────────────

wait_for_healthy() {
    local host_port="$1"
    local url="http://127.0.0.1:${host_port}/healthz"
    local elapsed=0

    info "Waiting for $url to return 200 (timeout=${HEALTH_TIMEOUT}s)"

    while [ "$elapsed" -lt "$HEALTH_TIMEOUT" ]; do
        if curl -sf -o /dev/null "$url" 2>/dev/null; then
            info "Health check passed after ${elapsed}s"
            return 0
        fi
        sleep "$HEALTH_CHECK_INTERVAL"
        elapsed=$((elapsed + HEALTH_CHECK_INTERVAL))
    done

    error "Health check timed out after ${HEALTH_TIMEOUT}s"
    return 1
}

# ── Caddy config ─────────────────────────────────────────────────────────────

write_caddy_config() {
    local active="$1"
    local inactive="$2"

    cat > "$CADDYFILE" <<CADDYEOF
# Shunt — Caddy reverse proxy configuration
# SPDX-License-Identifier: AGPL-3.0-only
#
# Active: ${active} | Standby: ${inactive}
# Auto-generated by ci/deploy.sh — manual edits will be overwritten.

:80 {
	reverse_proxy shunt-${active}:8080 {
		health_uri     /healthz
		health_interval 10s
		health_timeout  3s
	}

	log {
		output stdout
		format json
	}
}
CADDYEOF
}

reload_caddy() {
    info "Reloading Caddy configuration"
    docker compose -f "$COMPOSE_FILE" exec caddy \
        caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || \
    docker compose -f "$COMPOSE_FILE" exec -T caddy \
        caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || \
    warn "Caddy reload via compose exec failed; attempting API reload"
    # Fallback: Caddy API reload (if compose exec fails, e.g. no TTY)
    local caddy_admin="http://127.0.0.1:2019"
    if curl -sf "$caddy_admin/config/" >/dev/null 2>&1; then
        curl -sf -X POST "$caddy_admin/load" \
            -H "Content-Type: application/json" \
            -d @"$CADDYFILE" 2>/dev/null || true
    fi
}

# ── Main deploy flow ─────────────────────────────────────────────────────────

main() {
    local current
    current="$(get_current_color)"
    local target
    target="$(next_color "$current")"

    local target_port
    if [ "$target" = "blue" ]; then
        target_port=8081
    else
        target_port=8082
    fi

    info "Starting blue-green deploy: ${current} -> ${target}"

    # Step 1: Build fresh image
    info "Building Docker image"
    docker compose -f "$COMPOSE_FILE" build "shunt-${target}"

    # Step 2: Start the target (inactive) color
    info "Starting shunt-${target} container"
    docker compose -f "$COMPOSE_FILE" up -d "shunt-${target}"

    # Step 3: Wait for health check
    if ! wait_for_healthy "$target_port"; then
        error "Deploy aborted: shunt-${target} failed health check"
        info "Rolling back: stopping shunt-${target}"
        docker compose -f "$COMPOSE_FILE" stop "shunt-${target}"
        exit 1
    fi

    # Step 4: Switch Caddy to new color
    info "Switching Caddy to shunt-${target}"
    write_caddy_config "$target" "$current"
    reload_caddy

    # Step 5: Update active-color marker
    echo "$target" > "$ACTIVE_COLOR_FILE"
    info "Active color updated to ${target}"

    # Step 6: Drain and stop old color
    info "Draining old color shunt-${current} (${DRAIN_SECONDS}s grace period)"
    sleep "$DRAIN_SECONDS"
    info "Stopping shunt-${current}"
    docker compose -f "$COMPOSE_FILE" stop "shunt-${current}"

    info "Deploy complete: ${current} -> ${target}"
}

main "$@"
