#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Shunt — One-command rollback script
#
# Flips traffic back to the previous color:
#   1. Reads current active color from cfg/active-color
#   2. Determines the previous color
#   3. Starts the previous color container if stopped
#   4. Switches Caddy config to the previous color and reloads
#   5. Updates cfg/active-color marker
#   6. Stops the (now inactive) failed color
#
# Idempotent: safe to re-run at any point.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ACTIVE_COLOR_FILE="$PROJECT_ROOT/cfg/active-color"
CADDYFILE="$PROJECT_ROOT/cfg/Caddyfile"
COMPOSE_FILE="$PROJECT_ROOT/docker-compose.yml"

HEALTH_TIMEOUT=30
HEALTH_CHECK_INTERVAL=2

# ── Helpers ──────────────────────────────────────────────────────────────────

log() {
    local level="$1"; shift
    printf '{"time":"%s","level":"%s","msg":"%s"}\n' \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$level" "$*"
}

info()  { log "info"  "$@"; }
warn()  { log "warn"  "$@"; }
error() { log "error" "$@"; }

# ── Color logic ──────────────────────────────────────────────────────────────

get_current_color() {
    if [ -f "$ACTIVE_COLOR_FILE" ]; then
        cat "$ACTIVE_COLOR_FILE"
    else
        echo "blue"
    fi
}

previous_color() {
    local current="$1"
    if [ "$current" = "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# ── Health check ─────────────────────────────────────────────────────────────

wait_for_healthy() {
    local host_port="$1"
    local url="http://127.0.0.1:${host_port}/healthz"
    local elapsed=0

    info "Waiting for $url to return 200 (timeout=${HEALTH_TIMEOUT}s)"

    while [ "$elapsed" -lt "$HEALTH_TIMEOUT" ]; do
        if curl -sf -o /dev/null "$url" 2>/dev/null; then
            info "Health check passed after ${elapsed}s"
            return 0
        fi
        sleep "$HEALTH_CHECK_INTERVAL"
        elapsed=$((elapsed + HEALTH_CHECK_INTERVAL))
    done

    error "Health check timed out after ${HEALTH_TIMEOUT}s"
    return 1
}

# ── Caddy config ─────────────────────────────────────────────────────────────

write_caddy_config() {
    local active="$1"
    local inactive="$2"

    cat > "$CADDYFILE" <<CADDYEOF
# Shunt — Caddy reverse proxy configuration
# SPDX-License-Identifier: AGPL-3.0-only
#
# Active: ${active} | Standby: ${inactive}
# Auto-generated by ci/rollback.sh — manual edits will be overwritten.

:80 {
	reverse_proxy shunt-${active}:8080 {
		health_uri     /healthz
		health_interval 10s
		health_timeout  3s
	}

	log {
		output stdout
		format json
	}
}
CADDYEOF
}

reload_caddy() {
    info "Reloading Caddy configuration"
    docker compose -f "$COMPOSE_FILE" exec caddy \
        caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || \
    docker compose -f "$COMPOSE_FILE" exec -T caddy \
        caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || \
    warn "Caddy reload via compose exec failed; attempting API reload"
    local caddy_admin="http://127.0.0.1:2019"
    if curl -sf "$caddy_admin/config/" >/dev/null 2>&1; then
        curl -sf -X POST "$caddy_admin/load" \
            -H "Content-Type: application/json" \
            -d @"$CADDYFILE" 2>/dev/null || true
    fi
}

# ── Main rollback flow ───────────────────────────────────────────────────────

main() {
    local current
    current="$(get_current_color)"
    local previous
    previous="$(previous_color "$current")"

    local previous_port
    if [ "$previous" = "blue" ]; then
        previous_port=8081
    else
        previous_port=8082
    fi

    info "Rolling back: ${current} -> ${previous}"

    # Step 1: Start the previous color if it's stopped
    info "Starting shunt-${previous} container"
    docker compose -f "$COMPOSE_FILE" up -d "shunt-${previous}"

    # Step 2: Wait for health check
    if ! wait_for_healthy "$previous_port"; then
        error "Rollback failed: shunt-${previous} failed health check"
        exit 1
    fi

    # Step 3: Switch Caddy to previous color
    info "Switching Caddy to shunt-${previous}"
    write_caddy_config "$previous" "$current"
    reload_caddy

    # Step 4: Update active-color marker
    echo "$previous" > "$ACTIVE_COLOR_FILE"
    info "Active color updated to ${previous}"

    # Step 5: Stop the (now inactive) failed color
    info "Stopping shunt-${current}"
    docker compose -f "$COMPOSE_FILE" stop "shunt-${current}"

    info "Rollback complete: ${current} -> ${previous}"
}

main "$@"
